### ISSUE TITLE
慕名而来,我想请教下作者

### ISSUE THREAD

**Issue by DUWENINK** [sdcb/blog-data#2]
你上传的这些.linq文件都是些啥玩意,我打不开,也不知道怎么打开

**Comment by sdcb** [comment]
.linq文件是`LINQPad`文件的扩展名，你可以用`LINQPad 6`打开，`LINQPad 6`下载地址：https://www.linqpad.net/Download.aspx `LINQPad`是学习`C#`/`.NET`的好工具，特别适合用来做小`demo`、原型验证、教学等领域，用起来很方便。

另外其实`.linq`文件本质只是代码文本文件，你也可以直接用`Visual Studio`创建`C#`项目，然后将`.linq`文件中的代码复制粘贴到`Visual Studio`中，然后安装`.linq`中`xml`描述的`NuGet`包，引用有关的名字空间，一样也可以编译运行。
